### ISSUE TITLE
Proposed changes to configuration options

### ISSUE THREAD

**Issue by RobertoRDT** [evt-project/evt-viewer-angular#186]
In EVT 3 the single `config.json` file has been splitted in three different files:

- `edition_config.json`
- `file_config.json`
- `ui_config.json`

to which a fourth `editorial_conventions_config.json` file will be added as soon as this feature will be available. I noticed two problems with the current solution:

1. having four (or possibly more when a configuration file for 3DHOP or other complex features will be added) makes it more difficult to quickly switch between editions for didactic purposes and/or to test different edition files;
2. a few configuration options are less user-friendly compared to EVT 2

### 1. Switching configurations

A possible solution might be to have config sub-directories holding all the files related to a project and a simple, one line config.json file pointing to the configuration directory to be used, for instance:

- `config_VBD` for the Vercelli Book Digitale project
- `config_DOTR` for the Dream of the Rood edition files
- `config_CPD` for the Codice Pelavicino Digitale
- etc.

with `config.json` simply containing the following text:

```
{
	"config_dir": "config_VBD"
}
```
which might also be convenient for future very general stuff to be added to this file.

### 2. Configuration options improvements

The suggested enhancements are mostly related to the `edition_config.json` file:

- it is not clear what the user should do to hide / activate selected features such as edition levels and view modes, see f.i. the former in EVT 3

```
	"availableEditionLevels": [
		{
			"id": "diplomatic",
			"label": "diplomatic"
		},
		{
			"id": "interpretative",
			"label": "interpretative"
		},
		{
			"id": "critical",
			"label": "critical"
		}
	],
```

and in EVT 2

```
   "availableEditionLevel": [
      {
         "value": "critical",
         "label": "Critical",
         "title": "Critical edition",
         "visible": false
      },
      {
         "value": "diplomatic",
         "label": "Diplomatic",
         "title": "Diplomatic edition",
         "visible": false
      },
      {
         "value": "interpretative",
         "label": "Interpretative",
         "title": "Interpretative edition",
         "visible": true
      }
   ],
```

Basically, boolean values should be reintroduced explicitly in the sample configuration file, and the documentation changed to reflect their use, so that the editor doesn't have to delete what is not needed with all possible (bad) consequences when trying to change back the configuration. Also, instead of a `"disabled"` parameter an `"enabled"` one should be used to be consistent both with other uses of `"enabled"` in the configuration files (e.g. the available languages in the UI configuration file).

Very important for `"availableViewModes"` as well, since it's a long list, and possibly other options.

- general "switches" based on boolean values should be set immediately before the set of options they are related to, f.i. 	
 
`"showLists": true,`

should be placed immediately before the `"namedEntitiesLists"`.

- minor/general issues:
  - since no comments are possible in JSON files, we should use empty lines to order and distinguish configuration options
  - the `<event>` element goes in a `<listEvent>` and is not available to mark up text, it should probably be something like `<rs type="event" ref="#event_id">` (without pointy brackets in the config file)
  - I wonder if general layout stuff such as `"availableViewModes"` shouldn't go into the `ui_config.json` file, but it is fine in the current file as well

**Comment by ChiaraDipi** [comment]
For problem n° 1, the configuration has been divided in multiple files to facilitate both the reading of the configuration itself, which was becoming a very large file, and the reuse of the same configuration for different editions, which perhaps share the same configuration at the UI level, but use different files. 
If you also want to facilitate the change of configurations in order to switch from one edition to the other, we can 

- use the file_config.json, which was thought as the place "where to set the path(s) to the file(s) of the digital edition"; we can add a voice "configuration" like
```json
"configuration_paths": {
   "edition": "./config/edition_VDB.json",
   "ui": "./config/ui_VDB.json",
   "editorial_conventions": "./config/editorial_conventions_VDB.json",
}
```
- or add a 4th file "config_paths.json", containing the paths to all the other files:
```json
{
   "file": "./config/file_VDB.json",
   "edition": "./config/edition_VDB.json",
   "ui": "./config/ui_VDB.json",
   "editorial_conventions": "./config/editorial_conventions_VDB.json"
}
```
IMO, a config.json file which simply contains the indication for config folder, is not very user friendly. So if we add a 4th file, let's be clear!

FYI: `editorial_conventions_config.json` should already work! ;)

---

For problem n° 2, it is already like that! It's all written in the [Wiki page](https://github.com/evt-project/evt-viewer-angular/wiki/Edition-Configuration) where the available configuration is explained. Probably the config files in the build should be prepared better. 
If you prefer to establish that everything is disabled unless enabled from the configuration, no problem, but pls open a separate issue for this.

With regard to json file reorganization, we are open to suggestion for changes if you wanna share a "fixed" sample :) You can also open a Pull request with all the changes you propose, so that all the team can comment on them in a timely manner.

I don't understand which change you suggest when you say «the <event> element goes in a <listEvent> and is not available to mark up text, it should probably be something like <rs type="event" ref="#event_id"> (without pointy brackets in the config file)»

**Comment by RobertoRDT** [comment]
About problem 1: I would go for `file_config.json` to hold the configuration paths as suggested in @ChiaraDipi's reply.

About problem 2: I changed the configuration files according to my "make available options switches" suggestion in the sample_documents repository (`EVT3/v.alpha` directory). More improvements to come (also see below), but first  we should settle on `"enable(d)"` for boolean values.

About `<event>`: the problem with this element is that, unlike <persName>, <placeName> etc. it is not used in the edition text, but it is a child of <listEvent>, you don't have searchable <event>s in the text just as you don't have <person>s, <place>s etc. The equivalent to <persName>, <rolename> etc. for events would be <rs type="event" ref="[#id of the correspoding event in the list]".
